// This file is auto-generated by @hey-api/openapi-ts

export const $ExtendedDropdownEditorResponse = {
    required: ['dataTypeKey', 'items'],
    type: 'object',
    properties: {
        items: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        dataTypeKey: {
            type: 'string',
            format: 'uuid'
        }
    },
    additionalProperties: false
} as const;