// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetUmbracoExtendedDropdownEditorApiV1ItemsByDataTypeKeyData, GetUmbracoExtendedDropdownEditorApiV1ItemsByDataTypeKeyResponse } from './types.gen';

/**
 * @param data The data for the request.
 * @param data.dataTypeKey
 * @returns unknown OK
 * @throws ApiError
 */
export const getUmbracoExtendedDropdownEditorApiV1ItemsByDataTypeKey = (data: GetUmbracoExtendedDropdownEditorApiV1ItemsByDataTypeKeyData): CancelablePromise<GetUmbracoExtendedDropdownEditorApiV1ItemsByDataTypeKeyResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/ExtendedDropdownEditor/api/v1/items/{dataTypeKey}',
    path: {
        dataTypeKey: data.dataTypeKey
    }
}); };