// This file is auto-generated by @hey-api/openapi-ts

export type ExtendedDropdownEditorResponse = {
    items: Array<(string)>;
    dataTypeKey: string;
};

export type GetUmbracoExtendedDropdownEditorApiV1ItemsByDataTypeKeyData = {
    dataTypeKey: string;
};

export type GetUmbracoExtendedDropdownEditorApiV1ItemsByDataTypeKeyResponse = ((ExtendedDropdownEditorResponse));