name: 🏗️ Build
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: jcdcdev/jcdcdev.Umbraco.Github.Build@main
        with:
          project-name: jcdcdev.Umbraco.ExtendedDropdownEditor
          project-path: src/jcdcdev.Umbraco.ExtendedDropdownEditor/jcdcdev.Umbraco.ExtendedDropdownEditor.csproj
          npm-working-dir: src/jcdcdev.Umbraco.ExtendedDropdownEditor.Client
          npm-enabled: true
          umbraco-version: 15
          dotnet-version: "9"